name: build
run-name: build
on: [push]
jobs:
  build_linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            python3 -m venv .env
            source .env/bin/activate
            python3 -m pip install .
      - name: Test
        run: |
            git clone https://github.com/ODDSound/MTS-ESP.git ~/MTS-ESP
            sudo mkdir -p /usr/local/lib
            sudo cp ~/MTS-ESP/libMTS/Linux/x86_64/libMTS.so /usr/local/lib/
            source .env/bin/activate
            python3 -m pip install pytest
            pytest -v tests
  build_mac:
    runs-on: macos-14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
            python3 -m venv .env
            source .env/bin/activate
            python3 -m pip install .
      - name: Test
        run: |
            git clone https://github.com/ODDSound/MTS-ESP.git ~/MTS-ESP
            sudo mkdir -p "/Library/Application Support/MTS-ESP/"
            sudo cp ~/MTS-ESP/libMTS/Mac/x86_64_ARM/libMTS.dylib "/Library/Application Support/MTS-ESP/libMTS.dylib"
            source .env/bin/activate
            python3 -m pip install pytest
            pytest -v tests
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
            submodules: 'true'
      - name: Build
        run: |
          python3 -m venv .env
          .env/Scripts/Activate.ps1
          python3 -m pip install .
      # Windows CI tests currently fail with 'RuntimeError: IPC not available for MTS-ESP.'
      # - name: Test
      #   run: |
      #       git clone https://github.com/ODDSound/MTS-ESP.git
      #       mkdir "/Program Files/Common Files/MTS-ESP/"
      #       cp MTS-ESP/libMTS/Win/64bit/LIBMTS.dll "/Program Files/Common Files/MTS-ESP/LIBMTS.dll"
      #       .env/Scripts/Activate.ps1
      #       python3 -m pip install pytest
      #       pytest -v D:\a\mtsespy\mtsespy\tests
